[profile.default]
src = 'contracts'
test = 'test'
solc-version = "0.8.20"
script = 'scripts'
out = 'out'
libs = ['lib']

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "chainlink/=lib/chainlink/contracts/src/v0.8/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
]

libraries = []

cache = true
cache_path = 'cache'
broadcast = 'broadcast'
allow_paths = []
include_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = [1878, 5574]
fuzz_runs = 1024
invariant_runs = 256
invariant_depth = 15
invariant_fail_on_revert = false
invariant_call_override = false
ffi = false
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = []
extra_output_files = []
fuzz_max_local_rejects = 1024
fuzz_max_global_rejects = 65536
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = 'ipfs'
sparse_mode = false
build_info = false


[profile.ci]
fuzz_runs = 65536

[profile.local]
libraries = []


[profile.goerli]
libraries = [
    "contracts/utils/LineLib.sol:LineLib:0xd6EC4E0D237C72bE6e4d1d2a7d338D2C0281cf41",
    "contracts/utils/CreditLib.sol:CreditLib:0x31C3cBE78D63a8a0729fC5DB62Ca9013538979b8",
    "contracts/utils/CreditListLib.sol:CreditListLib:0x37C3456249016FB74F9741a2B51911f0B509539F",
    "contracts/utils/SpigotLib.sol:SpigotLib:0xdBcEce25E03dDba43ef21C15035dC9B2c5A72d79",
    "contracts/utils/EscrowLib.sol:EscrowLib:0x333551a0645d77d6d74B77F6DC6F87F93012c1Ad",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0x30ba55c483f5a09592ff72e36924512B3EB8Fe2b",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0x244c9A8746735C315B8eF914e4D70a017fF197D9",
]


[profile.sepolia]
libraries = [
    "contracts/utils/LineLib.sol:LineLib:0xCE95035acd9B5aE1304F652412dB849F8629F377",
    "contracts/utils/CreditLib.sol:CreditLib:0x18a744de156c9A1A6B6832fd4E47679146F087fA",
    "contracts/utils/CreditListLib.sol:CreditListLib:0xd3aC493cd5f02A5376849ccb494F233323AABE85",
    "contracts/utils/SpigotLib.sol:SpigotLib:0x3182c0f682B84D0586F7d2C38fa24a7E720d2359",
    "contracts/utils/EscrowLib.sol:EscrowLib:0x2492eF0F83F7041867eC067582d5157290e09B06",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0xa5De6E2A9503E227cA345f8aeb795A187a32F34e",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0x9dBeE9024C5DBd990783157c66ac65066cF277E4",
]

[profile.mainnet]
libraries = [
    "contracts/utils/LineLib.sol:LineLib:0xe639a9c07f39ED07F04f348D06f76dc80DC3EDeb",
    "contracts/utils/CreditLib.sol:CreditLib:0x713cCD56D4353224880Bdf4aB5BC1f9eB0947a5B",
    "contracts/utils/CreditListLib.sol:CreditListLib:0x9f48ccF9BA57ce89bb50ba9960a6B7C320183F19",
    "contracts/utils/SpigotLib.sol:SpigotLib:0x87fc87EC34C290963aE55CB42B4A481Ad3850E31",
    "contracts/utils/EscrowLib.sol:EscrowLib:0xA5C5f0c572c0f843d4234C6316D75fBD5A9C5bf1",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0x06e5E43210e76149996f344eDfC09D432FCaeBc9",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0x1C75806d3C160671a7620ca236C6B0203d0fCD13",
]

[profile.polygon]
libraries = [
    "contracts/utils/LineLib.sol:LineLib:0x1cbE547E9FE3f7D78484904d5FF812514B4B3d34",
    "contracts/utils/CreditLib.sol:CreditLib:0x98B08E3A2c7d5C963340A0D9a07938B817D93DB5",
    "contracts/utils/CreditListLib.sol:CreditListLib:0x6499BEdB9579E6c5CFb0cA19954Ae3eF367B5205",
    "contracts/utils/SpigotLib.sol:SpigotLib:0x3914000212295fD1AD008054b9B0496FbCDe3855",
    "contracts/utils/EscrowLib.sol:EscrowLib:0x11f294f583C087b1FB355b900Aa14155306979D5",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0x8a8B7B6acb79016074EB60fa4052305AbB656d0C",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0xEC51CCA52dD9c4d17b4B20E319695428414d051e",
]


[profile.arbitrum]
libraries = [
    "contracts/utils/LineLib.sol:LineLib:0x9f48ccF9BA57ce89bb50ba9960a6B7C320183F19",
    "contracts/utils/CreditLib.sol:CreditLib:0x87fc87EC34C290963aE55CB42B4A481Ad3850E31",
    "contracts/utils/CreditListLib.sol:CreditListLib:0xE7972F57252D81F8F8665E2691437146236b26fC",
    "contracts/utils/SpigotLib.sol:SpigotLib:0x89989dBe4CFa289dE6179e8d54EE755E471a4251",
    "contracts/utils/EscrowLib.sol:EscrowLib:0xF64fC04626d3f0CA01d7C23cA77110D2B5fd8893",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0x72bBE4dF62D5956e1d640D0fcb16DEe0A30B7049",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0xf2Fb1e2E4c0395ABA09ab28472b3495F5F480625",
]

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
