[profile.default]
src = 'contracts'
test = 'test'
script = 'script'
out = 'out'
libs = [
    'lib'
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "chainlink/=lib/chainlink/contracts/src/v0.8/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

libraries = []

cache = true
cache_path = 'cache'
broadcast = 'broadcast'
allow_paths = []
include_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = [
    1878,
    5574,
]
fuzz_runs = 256
invariant_runs = 256
invariant_depth = 15
invariant_fail_on_revert = false
invariant_call_override = false
ffi = false
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = []
extra_output_files = []
fuzz_max_local_rejects = 1024
fuzz_max_global_rejects = 65536
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = 'ipfs'
sparse_mode = false
build_info = false

[profile.gorli]

libraries = [
     "contracts/utils/CreditLib.sol:CreditLib:0x5497414F2daF410e02eA895e520B5B14aCB66ee4",
    "contracts/utils/CreditListLib.sol:CreditListLib:0xEce17172Fb59303A0228cEF858B6a8eac270204E",
    "contracts/utils/LineLib.sol:LineLib:0x3567E72FC9f9aDf06a2bcaa649b3cF6A9F657160",
    "contracts/utils/EscrowLib.sol:EscrowLib:0xd2598980E9BCe689116f4521971191F75812b244",
    "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0xef1a2c3b3b914eEe5dca1759dE43bFE05C791cf3",
    "contracts/utils/SpigotLib.sol:SpigotLib:0x8242C88bD53148f91d801C4A9b018cF9486fC037",
    "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0xA2CBbd23bBb41d19ec25dC1050C7390B4528780B"
]

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
