[profile.default]
src = 'contracts'
test = 'test'
script = 'scripts'
out = 'out'
libs = [
    'lib'
]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "chainlink/=lib/chainlink/contracts/src/v0.8/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

libraries = []

cache = true
cache_path = 'cache'
broadcast = 'broadcast'
allow_paths = []
include_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 20000
verbosity = 0
ignored_error_codes = [
    1878,
    5574,
]
fuzz_runs = 1024
invariant_runs = 256
invariant_depth = 15
invariant_fail_on_revert = false
invariant_call_override = false
ffi = false
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = []
extra_output_files = []
fuzz_max_local_rejects = 1024
fuzz_max_global_rejects = 65536
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = 'ipfs'
sparse_mode = false
build_info = false


[profile.ci]
fuzz_runs = 65536

[profile.local]
libraries = []


[profile.goerli]
libraries = [
            "contracts/utils/LineLib.sol:LineLib:0xd6EC4E0D237C72bE6e4d1d2a7d338D2C0281cf41",
            "contracts/utils/CreditLib.sol:CreditLib:0x31C3cBE78D63a8a0729fC5DB62Ca9013538979b8",
            "contracts/utils/CreditListLib.sol:CreditListLib:0x37C3456249016FB74F9741a2B51911f0B509539F",
            "contracts/utils/SpigotLib.sol:SpigotLib:0xdBcEce25E03dDba43ef21C15035dC9B2c5A72d79",
            "contracts/utils/EscrowLib.sol:EscrowLib:0x333551a0645d77d6d74B77F6DC6F87F93012c1Ad",
            "contracts/utils/SpigotedLineLib.sol:SpigotedLineLib:0x30ba55c483f5a09592ff72e36924512B3EB8Fe2b",
            "contracts/utils/LineFactoryLib.sol:LineFactoryLib:0x244c9A8746735C315B8eF914e4D70a017fF197D9"
        ]

[profile.mainnet]
libraries = [
]

[profile.arbitrum]
libraries = [
]

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'
